export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILED = 'LOAD_DATA_FAILED';

export const LOAD_DATA_DETAIL = 'LOAD_DATA_DETAIL';
export const LOAD_DATA_DETAIL_SUCCESS = 'LOAD_DATA_DETAIL_SUCCESS';
export const LOAD_DATA_DETAIL_FAILED = 'LOAD_DATA_DETAIL_FAILED';

export const CREATE_TUTOR = 'CREATE_TUTOR';
export const CREATE_TUTOR_SUCCESS = 'CREATE_TUTOR_SUCCESS';
export const CREATE_TUTOR_FAILED = 'CREATE_TUTOR_FAILED';

export const UPDATE_TUTOR = 'UPDATE_TUTOR';
export const UPDATE_TUTOR_SUCCESS = 'UPDATE_TUTOR_SUCCESS';
export const UPDATE_TUTOR_FAILED = 'UPDATE_TUTOR_FAILED';

export const DELETE_TUTOR = 'DELETE_TUTOR';
export const DELETE_TUTOR_SUCCESS = 'DELETE_TUTOR_SUCCESS';
export const DELETE_TUTOR_FAILED = 'DELETE_TUTOR_FAILED';