export const LOAD_SUBJECT = 'LOAD_SUBJECT';
export const LOAD_SUBJECT_SUCCESS = 'LOAD_SUBJECT_SUCCESS';
export const LOAD_SUBJECT_FAILED = 'LOAD_SUBJECT_FAILED';

export const LOAD_SUBJECT_DETAIL = 'LOAD_SUBJECT_DETAIL';
export const LOAD_SUBJECT_DETAIL_SUCCESS = 'LOAD_SUBJECT_DETAIL_SUCCESS';
export const LOAD_SUBJECT_DETAIL_FAILED = 'LOAD_SUBJECT_DETAIL_FAILED';

export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAILED = 'CREATE_SUBJECT_FAILED';

export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS';
export const UPDATE_SUBJECT_FAILED = 'UPDATE_SUBJECT_FAILED';

export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAILED = 'DELETE_SUBJECT_FAILED';